QueryChanges/QueryProjects: Enable retries
If there is an error in QueryChanges/QueryProjects we automatically
retry the request, but the retry always fails because
ChangesQueryProcessor/ProjectsQueryProcessor is not reusable [1]. Allow
retries by creating a fresh query processor instance on each try.

The same fix has already been done for QueryAccounts and QueryGroups by
change I2f7b02962.

[1]
AutoRetry: auto-retry of restapi.change.QueryChanges has failed [CONTEXT forced=true TRACE_ID="retry-on-failure-1573850225052-ef9c1609" ]
java.lang.IllegalStateException: ChangeQueryProcessor has already been used
        at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
        at com.google.gerrit.index.query.QueryProcessor.query(QueryProcessor.java:206)
        at com.google.gerrit.index.query.QueryProcessor.query(QueryProcessor.java:194)
        at com.google.gerrit.server.restapi.change.QueryChanges.query(QueryChanges.java:144)
        at com.google.gerrit.server.restapi.change.QueryChanges.apply(QueryChanges.java:121)
        at com.google.gerrit.server.restapi.change.QueryChanges.apply(QueryChanges.java:43)
        ...

Change-Id: Ia803075fcdfc062b223704a813753e43b5e6c75c
Signed-off-by: Edwin Kempin <ekempin@google.com>

Former-commit-id: 6170b8f56df2be3dd3e8ea20f2df006bf3df19bf