MailTransferException: Add missing serialVersionUID
Change-Id: I8cb26c09e7ee9cea9ad5d402ad56c120515c92bf

Former-commit-id: c186ed8db2bca88723fc6e64407ada10141bb0be