Add missing registration for VoteDeletedEvent
Without this, code trying to deserialize this event type will fail with:

com.google.gson.JsonParseException: Unknown event type: vote-deleted

Change-Id: I0a9db2e0ec117c4b47e689d0e7c596b38a4f1f4a

Former-commit-id: 9c72471ba33bdd9daf5be7fd69f094913ffa7f6a