Add missing import of symlink in download_jar.py
Missing import of `symlink` from the `os` module causes an error:

  Traceback (most recent call last):
    File "/work/gerrit/tools/download_jar.py", line 108, in <module>
      symlink(cache_ent, args.o)
  NameError: name 'symlink' is not defined

Change-Id: Ie0d6b6dbdd211f830a4443c98bd5ea3b3ab56e3e

Former-commit-id: 72a17019274f3412ef5b294d243a7c3fed8caab9