RetryHelper: Retry on LockFailureException if wrapped in StorageException
We want to automatically retry requests if there is a LOCK_FAILURE. If
the LockFailureException was wrapped in a StorageException we didn't
recognize it as LOCK_FAILURE for retry. E.g. LockFailureException is
wrapped in a StorageException if updating a sequence in NoteDb fails [1].

[1]
AutoRetry: restapi.change.CreateChange failed, retry with tracing enabled [CONTEXT forced=true TRACE_ID="retry-on-failure-1573981969624-cc31b57f" ]
com.google.gerrit.exceptions.StorageException: com.google.gerrit.git.LockFailureException: Failed to update refs/sequences/changes: LOCK_FAILURE
        at com.google.gerrit.server.notedb.RepoSequence.acquire(RepoSequence.java:285)
        at com.google.gerrit.server.notedb.RepoSequence.lambda$next$1(RepoSequence.java:223)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.google.gerrit.server.notedb.RepoSequence.next(RepoSequence.java:217)
        at com.google.gerrit.server.notedb.RepoSequence.next(RepoSequence.java:199)
        at com.google.gerrit.server.notedb.Sequences.nextChangeId(Sequences.java:114)
        at com.google.gerrit.server.restapi.change.CreateChange.createNewChange(CreateChange.java:326)
        at com.google.gerrit.server.restapi.change.CreateChange.apply(CreateChange.java:186)
        at com.google.gerrit.server.restapi.change.CreateChange.apply(CreateChange.java:103)
        at com.google.gerrit.httpd.restapi.RestApiServlet.lambda$invokeRestCollectionModifyViewWithRetry$7(RestApiServlet.java:793)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.google.gerrit.server.update.RetryHelper.executeWithTimeoutCount(RetryHelper.java:417)
        at com.google.gerrit.server.update.RetryHelper.executeWithAttemptAndTimeoutCount(RetryHelper.java:368)
        at com.google.gerrit.server.update.RetryHelper.execute(RetryHelper.java:271)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestEndpointWithRetry(RestApiServlet.java:820)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestCollectionModifyViewWithRetry(RestApiServlet.java:788)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:557)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        ...
Caused by: com.google.gerrit.git.LockFailureException: Failed to update refs/sequences/changes: LOCK_FAILURE
        at com.google.gerrit.git.RefUpdateUtil.checkResult(RefUpdateUtil.java:126)
        at com.google.gerrit.server.notedb.RepoSequence.acquire(RepoSequence.java:280)
        ... 215 more

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: If8027bc551db4fa6683f4d56ddbb45f7b05c83ee

Former-commit-id: 1716191ecdc609c1613949080bf3c238f5982b1f