Update git submodules
* Update plugins/replication from branch 'master'
  to b44768838ff462b373e932d3d5c340612e28f940
  - Merge branch 'stable-3.0'
    
    * stable-3.0:
      HttpResponse: Specify charset in constructor of InputStreamReader
      Add auto-reload as background task
      Avoid double slash in REST calls made from the GerritRestApi
    
    AutoReloadConfigDecorator: Add unused assignment to fix the now
    mandatory errorprone check for unused returned Future values.
    
    Change-Id: I7b809b520b8ce35658d01bca2a6b503c5200713e
    
  - HttpResponse: Specify charset in constructor of InputStreamReader
    
    When all error prone warnings are enabled the DefaultCharset
    bug pattern is reported:
    
      plugins/replication/src/main/java/com/googlesource/gerrit/plugins/replication/HttpResponse.java:37:
      error: [DefaultCharset] Implicit use of the platform default charset, which can
      result in differing behaviour between JVM executions or incorrect behavior if
      the encoding of the data source doesn't match expectations.
          reader = new InputStreamReader(response.getEntity().getContent());
                   ^
        (see https://errorprone.info/bugpattern/DefaultCharset)
    
    Change-Id: I7a8e0d39fdcd06e7d73d7ed89d0f12f4232b2600
    
  - Add auto-reload as background task
    
    Delegate the auto-reload of replication.config to a background
    task. The scheduling isn't configurable, which is fine because
    it wasn't configurable before this change either.
    
    Change-Id: I73c0c383c2ff3ef05d6b7bbd3ac3a665697cad68
    
  - Avoid double slash in REST calls made from the GerritRestApi
    
    Change-Id: I2742411bc801e113e487bf5c9cbb26ede35d2bd5
    

Former-commit-id: c58faf8c2652ae040f3490a02cdd9ee03f537828