Show change screen even if loading file list fails
E.g. loading the file list fails if the patch set contains an
object that exceeds the size limit. In this case the Files REST
endpoint returns 404 Not Found with the following message:
"com.google.common.util.concurrent.UncheckedExecutionException:
org.eclipse.jgit.errors.LargeObjectException: unknown object exceeds
size limit"

In this case we can still display the change screen without file list.
This is better then failing completely since it allows the user to
abandon the change.

To inform the user that loading the file list has failed an error
message is displayed.

Change-Id: I658fbc291261d522ec69ee3c5c7ac00a93311de2
Signed-off-by: Edwin Kempin <ekempin@google.com>

Former-commit-id: c9394a1ca297d73226e94c4daba8ba43cabeb35f