Change kind cache: Don't fail if prior ps has no parent, but next ps has 1 parent
This case failed with:

[2016-11-14 18:44:53,805] [ReceiveCommits-1] ERROR com.google.gerrit.server.git.ReceiveCommits : [com.google.gerrit.acceptance.api.change.ChangeIT_changeNoParentToOneParent_project-1479177893785-ed68f500]Can't insert change/patch set for com.google.gerrit.acceptance.api.change.ChangeIT_changeNoParentToOneParent_project
com.google.gerrit.extensions.restapi.RestApiException: Error inserting change/patchset
  at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:274)
  at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:1)
  at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:851)
  at com.google.gerrit.server.git.ReceiveCommits.processCommands(ReceiveCommits.java:605)
  at com.google.gerrit.server.git.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:89)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:221)
  at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:200)
  at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:55)
  at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:99)
  at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:131)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:417)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gerrit.server.git.UpdateException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
  at com.google.gerrit.server.git.BatchUpdate.executeUpdateRepo(BatchUpdate.java:697)
  at com.google.gerrit.server.git.BatchUpdate.execute(BatchUpdate.java:421)
  at com.google.gerrit.server.git.BatchUpdate.execute(BatchUpdate.java:673)
  at com.google.gerrit.server.git.BatchUpdate.execute(BatchUpdate.java:668)
  at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:849)
  ... 16 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
  at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
  at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899)
  at com.google.gerrit.server.change.ChangeKindCacheImpl.getChangeKind(ChangeKindCacheImpl.java:338)
  at com.google.gerrit.server.git.ReplaceOp.updateRepo(ReplaceOp.java:194)
  at com.google.gerrit.server.git.BatchUpdate.executeUpdateRepo(BatchUpdate.java:681)
  ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
  at org.eclipse.jgit.revwalk.RevCommit.getParent(RevCommit.java:353)
  at com.google.gerrit.server.change.ChangeKindCacheImpl$Loader.call(ChangeKindCacheImpl.java:245)
  at com.google.gerrit.server.change.ChangeKindCacheImpl$Loader.call(ChangeKindCacheImpl.java:1)
  at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
  ... 25 more

Change-Id: I689b703d4912d54bfc659def577b689fc1cda887
Signed-off-by: Edwin Kempin <ekempin@google.com>

Former-commit-id: d49bd17f7a4a2e464dc85bfab0aff0a4be807e4d