Do not fail with NPE if context path of request is null
This may result in the following error:

com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NullPointerException: while trying
to invoke the method java.lang.String.isEmpty() of an object loaded from
local variable 'path'
  at com.google.gerrit.httpd.WebSession.<init>(WebSession.java:79)
  while locating com.google.gerrit.httpd.WebSession
    for parameter 0 at
  com.google.gerrit.httpd.HttpCurrentUserProvider.<init>(HttpCurrentUserProvider.java:27)
  while locating com.google.gerrit.httpd.HttpCurrentUserProvider
  while locating com.google.gerrit.server.CurrentUser

Change-Id: I6a2e5324f4efb1e141309aec2e8cc47ead7af4a5
Signed-off-by: Edwin Kempin <edwin.kempin@sap.com>

Former-commit-id: 1a52caed04eb776be08dd4e548e156c59153c8d2