Init: Catch NoClassDefFoundError when initializing plugins
The InitStep interface was moved to a different package in 2.11.

If the plugins folder contains a plugin that was built against API
version 2.10 or earlier, and implements the InitStep interface, this
will cause NoClassDefFoundError to be raised when initializing the
plugin.

Catch the error and display a warning message, instead of failing
with a stack trace.

Add newlines on existing warning messages.

Change-Id: I3b3839987d5f821beb085008fabbca4196860fd8

Former-commit-id: 7c3651832a5abefd1b9d046f8aac01a728914528