NoSuchGroupException: Remove unused constructor
Change-Id: Ie26ec1e0442c9c59d9f00f5238825ea45e72f0dc

Former-commit-id: 8c5ab445aa2e8a8f1a6bbede32a59e199c9b25b3