QueryAccount/QueryGroups: Enable retries
If there is an error in QueryAccount/QueryGroups we automatically retry
the request, but the retry always fails because
AccountQueryProcessor/GroupQueryProcessor is not reusable [1]. Allow
retries by creating a fresh query processor instance on each try.

[1]
AutoRetry: auto-retry of restapi.account.QueryAccounts has failed [CONTEXT forced=true TRACE_ID="retry-on-failure-1573791374279-221012e6" ]
java.lang.IllegalStateException: AccountQueryProcessor has already been used
        at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
        at com.google.gerrit.index.query.QueryProcessor.query(QueryProcessor.java:206)
        at com.google.gerrit.index.query.QueryProcessor.query(QueryProcessor.java:194)
        at com.google.gerrit.index.query.QueryProcessor.query(QueryProcessor.java:178)
        at com.google.gerrit.server.restapi.account.QueryAccounts.apply(QueryAccounts.java:211)
        at com.google.gerrit.server.restapi.account.QueryAccounts.apply(QueryAccounts.java:55)
        ...

Change-Id: I2f7b02962d65d98e83531ffb5b81d4e9287d6fbb
Signed-off-by: Edwin Kempin <ekempin@google.com>
(cherry picked from commit 41e91be77a5634b225bb00b3e6e9d7b2f3314aed [formerly bfce38654f1eb352cbcbd24d9bc18957770864af])

Former-commit-id: 68961912b7fd4a7edec9e625b9b37e7e1a6bcb1e