Fix GroupsIT#pushToGroupBranchIsRejectedForAllUsersRepo with GroupNoteDbMode == WRITE
The test was failing with [1]. The test wrongly tried to create the
group branch although it already existed. Only when noteDb.groups.read
== true was set in addition to noteDb.groups.write == true the branch
creation was skipped.

[1]
java.lang.AssertionError: Not true that <LOCK_FAILURE> is equal to <NEW>
	at com.google.gerrit.acceptance.api.group.GroupsIT.createGroupBranch(GroupsIT.java:1171)
	at com.google.gerrit.acceptance.api.group.GroupsIT.assertPushToGroupBranch(GroupsIT.java:906)
	at com.google.gerrit.acceptance.api.group.GroupsIT.pushToGroupBranchIsRejectedForAllUsersRepo(GroupsIT.java:872)
	...

Change-Id: Ifbf345940c0a5f25f8817dc8e65098de2caba0fe
Signed-off-by: Edwin Kempin <ekempin@google.com>

Former-commit-id: 4c0878fb234f63fe86fb5de390da0621c2384729