Fix transitive load of GWT_PLUGIN_DEPS for in-tree plugin builds
If any plugin that depends on GWT_PLUGIN_DEPS (e.g. importer, reviewers)
is included in the gerrit in-tree build, running the command:

  bazel test //...

fails with:

  ERROR: gerrit/plugins/importer/tools/eclipse/BUILD:2:1:
  file '//tools/bzl:plugin.bzl' does not contain symbol 'GWT_PLUGIN_DEPS'

Bug: Issue 10855
Change-Id: I90ca42e0425d3749525e27b3c876de2fee1221ab

Former-commit-id: beb365c081d9a20e8a42c83175b0cf416ec7b0a7