Allow to build api with Java 8
Java 8's javadoc fails hard on unknown HTML tags. Due some
documentation code snippets that contain generics and lacked a
{@code...}, the code got picked up as html, which made the target fail
like:

  [...]/extensions/registration/DynamicSet.java:64: error: unknown tag: Foo
   *   DynamicSet.setOf(binder(), new TypeLiteral<Thing<Foo>>() {});

We insert the needed {@code...} to make the build pass for Java 8.

Change-Id: I430b8eb9f2f158c2c7a2a7a8d93446eff3253529

Former-commit-id: 0da441ef879b2514b8f1684d3247e02ba8b69618