QuotaException: Add missing serialVersionUID
Change-Id: I064d5d83faf3b910b9c575eec782d4dcb3c5a173

Former-commit-id: 24e126bc1294e97fdc31a71d7269f21a997af19d