Fix unloading of plugins
When two plugins, say pluginA, and pluginB have been loaded, and
pluginA is removed from $sitePath/plugins, pluginA gets stopped, and a
cleaning run is ordered. But this cleaning run cleans both plugins and
both plugins have their jars removed. This leaves pluginB visible to
gerrit although it's backing jar is gone. Upon calling not yet
initialized parts of pluginB (e.g.: viewing not yet viewed
Documentation pages on pluginB), exceptions as

  java.lang.IllegalStateException: zip file closed
          at java.util.zip.ZipFile.ensureOpen(ZipFile.java:420)
          at java.util.zip.ZipFile.getEntry(ZipFile.java:165)

get thrown. Additionally, it seems that since commit
663719c02474a6a93554b5d528188a03b609e713 [formerly fac27716d8e1883c78c2c7313c31f9393c25a1a7] a plugin's class loader is
garbage collected only after the plugin itself is garbage collected,
as plugins hold a reference to their class loader. Thereby making the
burden of using ReferenceQueue and WeakReferences unneeded.

As the solution to those two issues cannot be properly isolated we fix
both in one go. We
* stop enqueuing a plugin for cleaning up already upon creating of the
  plugin,
* get rid of using ReferenceQueue and WeakReference,
* introduce a single point to unload a plugin, and
* stop determining how many handles have to be cleaned by subtracting
  the number of running handles from the number of all (i.e.: running,
  disabled, and to be cleaned) handles, as this avoids settling in the
  cleaning thread, when having disabled plugins.
Thereby, we can reliably unload a single plugin, without affecting the
other loaded plugins.

Change-Id: I962b4009907c1815cc5859c06343ca9a0de7a293

Former-commit-id: 35d66cbcfe44b9388d03178ba23ef091de700ae3