Revert "InlineEdit: Allow to upload change edit with git push"
Cannot add patch set to 134391 of platform/tools/base
com.google.gerrit.server.git.InsertException: Error inserting change/patchset
	at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:269)
...
Caused by: java.lang.NullPointerException
	at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest$1.call(ReceiveCommits.java:2044)
	at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest$1.call(ReceiveCommits.java:2040)
	at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:222)
	at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:201)
	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:55)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:98)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.doRun(TrustedListenableFutureTask.java:139)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:92)
	... 3 more

This reverts commit 57bd2d38fab980fa9ac798bb6903a0dd36272776 [formerly d07bb339969e66bdb65b0f6b88c3ea43ce88d316].

Change-Id: Id5f7f5d5c945643f3e899992614d9637e7f68966

Former-commit-id: 744a968d673f8b76891c8fd41fc61f8ff5e90916