LimitExceededException: Add missing serialVersionUID
Change-Id: Idfd46326cd707327463096d8a0c7384f7835cd2f

Former-commit-id: 9cfbd05d58d05274b921d5986f6a687d769f971c