CreateChangeIT: Fix flaky test
This test was occasionally failing with "Not found" on the new change.
After the previous commit, it became clear that this was multiple
changes with the same Change-Id (as opposed to a Lucene indexing
race, which would have been harder to track down):

 FAILURE com.google.gerrit.acceptance.rest.change.CreateChangeIT createNewChange: Multiple changes found for I456d43543ea95b7b39ea3ebc5150db2493efc943
 com.google.gerrit.extensions.restapi.ResourceNotFoundException: Multiple changes found for I456d43543ea95b7b39ea3ebc5150db2493efc943
         at com.google.gerrit.server.change.ChangesCollection.parse(ChangesCollection.java:99)
         at com.google.gerrit.server.api.changes.ChangesImpl.create(ChangesImpl.java:96)
         at com.google.gerrit.acceptance.rest.change.CreateChangeIT.assertCreateSucceeds(CreateChangeIT.java:94)
         at com.google.gerrit.acceptance.rest.change.CreateChangeIT.createNewChange(CreateChangeIT.java:66)

The reason for this is that the computed Change-Id in CreateChange
only takes into account the current branch tip, subject, and author.
In CreateChangeIT, the branch tip is the same (nonexistent) and the
subject is a constant, meaning if the tests run fast enough, the
timestamp is the same as well.

Fix this by setting the current millis provider as in some other
tests.

Change-Id: Ifc6d478f8bd633a1996c8352869ffb670ca32325

Former-commit-id: f8d957ea634cd05522bbb47c0a8a4049949dc8cb