Update git submodules
* Update plugins/replication from branch 'master'
  to 08862c06001ff24892c5459ead7ebf738893d664
  - Merge branch 'stable-2.15'
    
    * stable-2.15:
      GerritSshApi: strip 'gerrit+' instead of leaving only it
    
    Change-Id: I1490a38456ce33670624ae3c8bc966a6a6fab5e0
    
  - GerritSshApi: strip 'gerrit+' instead of leaving only it
    
    [2018-04-12 22:30:04,038] [ReplicateTo-bitbucket-1] ERROR com.googlesource.gerrit.plugins.replication.GerritSshApi : Error creating remote repository at gerrit+ssh://gerrit-bitbucket@localhost/:
    Exception: org.eclipse.jgit.errors.TransportException: gerrit+: host must not be null.
    Command: gerrit create-project --branch refs/heads/master repo/test
    Output:
    org.eclipse.jgit.errors.TransportException: gerrit+: host must not be null.
    
    Change-Id: Ib53258625b3677f621d2e7e9d6df4b04a94a921d
    Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
    

Former-commit-id: 9e85fe4035265732f66fa0728fb7b5cff054d788