Resolve BouncyCastleProvider at runtime
The maven setup always has BouncyCastle available, so this compiled
fine. But when run against a site without BouncyCastle installed, this
was causing NoClassDefFoundErrors. Instead, use reflection when setting
up the provider, and turn reflection errors into relatively more
friendly Guice errors.

Change-Id: I4adfafe4d13e3524ad15bf1a52cc17d015b9d322

Former-commit-id: 3650d0ef37715f2c38576c48c5a214b5f116d931