Bump to powermock 1.6.2 and to compatible easymock 3.3.1
We were at powermock 1.5 and easymock 3.2. However, powermock 1.5
requires easymock 3.1. This mismatch in easymock versions caused tests
for plugins to fail with

  org.powermock.reflect.exceptions.FieldNotFoundException: No instance
    field of type "org.easymock.internal.MocksControl$MockType" could be
    found in the class hierarchy of org.easymock.internal.MocksControl.

For example its-phabricator worked around it by providing and forcing
easymock 3.1. In order to be able to get rid of such workarounds, we
bump to powermock 1.6.2 and easymock 3.3.1, which are compatible
versions again.

Although easymock requires to bump objenesis only to 1.3, we
nonetheless bump it objenesis to 2.1 as powermock 1.6.2 requires
objenesis 2.1.

Change-Id: Ie61f51b937b8753f933b66d61f62c174b51c5ea6

Former-commit-id: c5f6b665a0307da1a5117c6245c83a030cf69888