Rewrite plugin WrappedContext using reflection based proxy
Gerrit sources do not compile directly against servlet 3.0 because
WrappedContext implements the ServletContext interface.  In the 3.0
API a number of new methods and types were added which are not
available in 2.5.  Unfortunately WrappedContext needs to compile for
both APIs in order to support the "odd" linking case at Google.

Implement the ServletContext using an indirect reflection based proxy,
with supported methods delgated to a Handler implementation.  This
allows the source code to compile against either servlet API version,
with newer methods throwing NoSuchMethodError.

Change-Id: Id41e37d4cacdd0cb1c90828fc4c2436b7e1284a7

Former-commit-id: 6af4c8104bf66ef40e7da70ab4290a9134af11b1