Fixed the full name of the MAVEN2_CLASSPATH_CONTAINER
After the Eclipse settings were changed to be compatible with the Eclipse
3.7 and the m2e (commit: 6bec5656cd382dd1a0f55f667cee60829dfef609 [formerly a68b89fd533e5beb7ed71fa198ac543fb3e81cfb]) the full
name of the MAVEN2_CLASSPATH_CONTAINER wasn't updated.  This broke the
gwtui_dbg.launch configuration as no maven dependecies were found any more.
Launching this configuration would fail with the
java.lang.NoClassDefFoundError: com/google/gwt/dev/DevMode

Change-Id: I6040d856dbe1880db47dc6a6e68063cebba722e4
Signed-off-by: Sasa Zivkov <zivkov@gmail.com>

Former-commit-id: 2710d065ac586c4394f25bac6f30994b1da79dca