Keep status:closed's limit below MySQL Connector/J's hard limit
Since MySQL Connector/J 5.1.21 does not allow limits above 50M rows
and aborts them with

  java.sql.SQLException: setMaxRows() out of range. 2147483647 > 50000000.

we cannot use MAX_VALUE as limit for plain "status:closed" queries. As
50M seems big enough for general use anyways, we use the 50M limit.

Bug: 2392
Change-Id: I70d3446b3fd3a140f7cdd0591803bec5df050484

Former-commit-id: 5303ffc1ab74d41a81011d31f5c0993857879db6