Update git submodules
* Update plugins/delete-project from branch 'master'
  to 4223c71d319b04c6b42566d2d12adca20734526d
  - Merge branch 'stable-3.0'
    
    * stable-3.0:
      FilesystemDeleteHandler: Fix misused week year flagged by error prone
      Upgrade bazlets to latest stable-2.16 to build with 2.16.12 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.17 API
      .bazelrc: Update 'strict_action_env' flag
      Switch required bazel version to 0.29.1
      Make build tests name consistent with stable-2.15
      Upgrade bazlets to latest stable-2.16
      Upgrade bazlets to latest stable-2.15
      Bump required bazel version to 1.0.0rc2
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
      Upgrade bazlets to latest stable-2.16 to build with 2.16.11.1 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.16 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.15 API
      Upgrade bazlets to latest stable-2.16 to build with 2.16.10 API
      Upgrade bazlets to latest stable-2.16
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.16 to build with 2.16.9 API
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Align tests target name prefix with plugin name
      Upgrade bazlets to latest stable-2.15 to build with 2.15.14 API
      Upgrade bazlets to latest revision on stable-2.16
      Upgrade mockito-core to 2.28.2
      Make transitive starlark loads explicit
      Make transitive starlark loads explicit
    
    Change-Id: I8fa9f64537030cbc631025e06108c47c7979c071
    
  - Merge branch 'stable-2.16' into stable-3.0
    
    * stable-2.16:
      FilesystemDeleteHandler: Fix misused week year flagged by error prone
      Upgrade bazlets to latest stable-2.16 to build with 2.16.12 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.17 API
      .bazelrc: Update 'strict_action_env' flag
      Switch required bazel version to 0.29.1
      Make build tests name consistent with stable-2.15
      Upgrade bazlets to latest stable-2.16
      Upgrade bazlets to latest stable-2.15
      Bump required bazel version to 1.0.0rc2
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
      Upgrade bazlets to latest stable-2.16 to build with 2.16.11.1 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.16 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.15 API
      Upgrade bazlets to latest stable-2.16 to build with 2.16.10 API
      Upgrade bazlets to latest stable-2.16
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.16 to build with 2.16.9 API
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Align tests target name prefix with plugin name
      Upgrade bazlets to latest stable-2.15 to build with 2.15.14 API
      Upgrade bazlets to latest revision on stable-2.16
      Upgrade mockito-core to 2.28.2
      Make transitive starlark loads explicit
      Make transitive starlark loads explicit
    
    Change-Id: If70f8a70d96525645b0037b9d9978db5dba83047
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      FilesystemDeleteHandler: Fix misused week year flagged by error prone
      Upgrade bazlets to latest stable-2.15 to build with 2.15.17 API
    
    Change-Id: I1a359dd758ffecfc10f149b90da33999e29b379b
    
  - FilesystemDeleteHandler: Fix misused week year flagged by error prone
    
    The recent error prone version 2.3.3, that is included in most recent
    Bazel@HEAD reports MisusedWeekYear pattern:
    
      Building plugins/delete-project/libdelete-project__plugin-class.jar
      FilesystemDeleteHandler.java:45: error: [MisusedWeekYear] \
      Use of "YYYY" (week year) in a date pattern without "ww"
      (week in year). You probably meant to use "yyyy" (year) instead.
      DateTimeFormatter.ofPattern("YYYYMMddHHmmss")
                                   ^
      (see https://errorprone.info/bugpattern/MisusedWeekYear)
    
    Bug: Issue 11658
    Change-Id: I17bbd72a57137e897a992280ee954aeba4d4c28c
    
  - Upgrade bazlets to latest stable-2.16 to build with 2.16.12 API
    
    Change-Id: Ie2cc612f5b7c0a4e7aaef07ffcca827979e9d206
    
  - Upgrade bazlets to latest stable-2.15 to build with 2.15.17 API
    
    Change-Id: I53097544777cc685bcf990107e0a2e0b400a4915
    
  - .bazelrc: Update 'strict_action_env' flag
    
    For the rationale see the change in gerrit core [1].
    
    IIUC:
    - The reason that '--action_env=PATH' is required is npm (Issue 10372),
    - which in turn was only needed because of PolyGerrit support,
    - which was not available in earlier stable branches than stable-2.16
      for this plugin.
    - From stable-3.0 onwards, delete-project is a core plugin and support
      for standalone builds were removed, and this Bazel flag isn't
      necessary any longer as it's taken from the main gerrit project.
    
    This means that when merging this upwards to stable-3.0 and beyond, this
    can be ignored.
    
    [1]: https://gerrit-review.googlesource.com/c/gerrit/+/238112
    
    Change-Id: Idad3a41eabb868b3f1b0f7115a90223105d64ee9
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Switch required bazel version to 0.29.1
      Make build tests name consistent with stable-2.15
    
    Change-Id: I3bacaa56df4d827b4a71d5b182280658f2bb71ac
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Switch required bazel version to 0.29.1
      Make build tests name consistent with stable-2.15
    
    Change-Id: I9eb3db10a7c4d4624949b6b3759bccecaaf966ee
    
  - Switch required bazel version to 0.29.1
    
    Based on the corresponding core change series started with Ib48fdbb6.
    
    Change-Id: I9d2e3d32e426eaa4d4c768bb2dbdd76ae97e1bcc
    
  - Make build tests name consistent with stable-2.15
    
    Change-Id: I1b580a9e300ec8d0d12b94bf8299d9ffb821c345
    
  - Upgrade bazlets to latest stable-2.16
    
    Includes further fixes for --incompatible_disallow_legacy_java_provider.
    
    Change-Id: I09124f0999edb0086ae509de56ffaa0b05024ff2
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade bazlets to latest stable-2.15
      Bump required bazel version to 1.0.0rc2
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I8566c68c4e2cf777aafa7602e69d00618e583b19
    
  - Upgrade bazlets to latest stable-2.15
    
    Includes further fixes for --incompatible_disallow_legacy_java_provider.
    
    Change-Id: Ibece8324414affb6442a39caf9dcec1d7a37f4c0
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Bump required bazel version to 1.0.0rc2
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I50790acf74d4832a8994b72e4b0768177fc5d960
    
  - Bump required bazel version to 1.0.0rc2
    
    Change-Id: I054b83b3df7d9fda5539f9e6ab43da6d2e665715
    
  - Upgrade bazlets to latest stable-2.14
    
    Includes further fixes for --incompatible_disallow_legacy_java_provider
    
    Change-Id: If209b2607558a4b253147bb37bdc6af7c39d1144
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I3eae342cdad7494df4b39c2e7c28a40258798906
    
  - Upgrade bazlets to latest stable-2.15
    
    Includes the following fixes:
    
    - Bazel: Add fixes for --incompatible_load_python_rules_from_bzl
    - Bazel: Export rules_python in plugin API
    - Support bazelisk or bazel in tools/eclipse/project.py
    - Rework imports in project.py
    - Update project.py to use argparse
    - Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
    
    Change-Id: If06e157079ef79120ef02b1023987d1f98451cf1
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: Iaf320d73afff61d7534830566e5981516bae1823
    
  - Upgrade bazlets to latest stable-2.14
    
    Includes the following fixes:
    
    - Bazel: Add fixes for --incompatible_load_python_rules_from_bzl
    - Bazel: Export rules_python in plugin API
    - Support bazelisk or bazel in tools/eclipse/project.py
    - Rework imports in project.py
    - Update project.py to use argparse
    - Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
    
    Also adds a .bazelversion file specifying version 0.29.0 which is
    used by bazelisk (if installed).
    
    Change-Id: If06e157079ef79120ef02b1023987d1f98451cf1
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
    
    Change-Id: If8e022e70be8942aa8c90b39c6fef790df1378e2
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
    
    Change-Id: I920ed0e4f6eba4cc45ee696a338a91c37f2f03a1
    
  - Bazel: Add fixes for --incompatible_load_java_rules_from_bzl
    
    Change-Id: Ia8fd326989b34705557f5188c07c1035bf6628e4
    
  - Upgrade bazlets to latest stable-2.16 to build with 2.16.11.1 API
    
    Change-Id: I368123793bd78f7353d117c32f6a705397c662f0
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade bazlets to latest stable-2.15 to build with 2.15.16 API
      Upgrade bazlets to latest stable-2.15 to build with 2.15.15 API
    
    Change-Id: I361db3a687168c8222d09e19149a3528678f017d
    
  - Upgrade bazlets to latest stable-2.15 to build with 2.15.16 API
    
    Change-Id: Ic10b50eebfe0aae23517e50013b937f63e99014b
    
  - Upgrade bazlets to latest stable-2.15 to build with 2.15.15 API
    
    Change-Id: Ia0a7c7754fa077eae2fbc0f1c1fa4cb6df3b6350
    
  - Upgrade bazlets to latest stable-2.16 to build with 2.16.10 API
    
    Change-Id: I3a276ac33e46f8db865abb1cd537ef56bd6a4eea
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I6bb325a92cbe62d470b109be3dfe137a2643cb84
    
  - Upgrade bazlets to latest stable-2.16
    
    - download_file.py: Synchronize curl options with gerrit core
    - Bazel: Make build tool chain forward compatible
    
    Change-Id: Ic57b35e489a4a95a2e8a259741c79d38ba657047
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I6d55c04b7f2575ad76574eeedef56d5803cb1272
    
  - Upgrade bazlets to latest stable-2.15
    
    - download_file.py: Synchronize curl options with gerrit core
    
    Change-Id: Ic57b35e489a4a95a2e8a259741c79d38ba657047
    
  - Upgrade bazlets to latest stable-2.14
    
    - download_file.py: Synchronize curl options with gerrit core
    
    Change-Id: Ic57b35e489a4a95a2e8a259741c79d38ba657047
    
  - Upgrade bazlets to latest stable-2.15
    
    Change-Id: I590c7c1129a08932b1c5e91a79a503cad345f162
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I5e1c7469bd43468ac0042e7fa93997023ae5c4f6
    
  - Upgrade bazlets to latest stable-2.14
    
    Change-Id: I4ed9d2aa8b3d3a7e008a770504e1004dd31c8a9f
    
  - Upgrade bazlets to latest stable-2.16 to build with 2.16.9 API
    
    Change-Id: Id94b6587b12653b3c4bab9eb9f44d10bf95061e3
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade bazlets to latest stable-2.15
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: I7b8c2ea4ae23ced880334c9116165c6002d23f52
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Upgrade bazlets to latest stable-2.14
    
    Change-Id: Ib0d3546cf4fd364cdd77ad03a9ae39808f8473dd
    
  - Upgrade bazlets to latest stable-2.15
    
    - Bazel: Remove iteration over depset
    
    Change-Id: Iffb4fda899eeb64847f244953d9bcb3b044cfe54
    
  - Upgrade bazlets to latest stable-2.14
    
    - Bazel: Remove iteration over depset
    
    Change-Id: Iffb4fda899eeb64847f244953d9bcb3b044cfe54
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Align tests target name prefix with plugin name
      Upgrade bazlets to latest stable-2.15 to build with 2.15.14 API
    
    Change-Id: Icbb2fd10cb193f8f9839a28789c8c18668d22f04
    
  - Align tests target name prefix with plugin name
    
    Change-Id: Ia6cd289280b7b2fdf46ca49ccb0dd1485edd56a4
    
  - Upgrade bazlets to latest stable-2.15 to build with 2.15.14 API
    
    Change-Id: I77ca8189cb4af489d25137c1a19b4d6c013ac1e8
    
  - Merge branch 'stable-2.15' into stable-2.16
    
    * stable-2.15:
      Upgrade mockito-core to 2.28.2
      Make transitive starlark loads explicit
      Make transitive starlark loads explicit
    
    Change-Id: I581f49e28b7c842469cb5e7199925c9f4aff4263
    
  - Upgrade bazlets to latest revision on stable-2.16
    
    Includes the following changes to fix the build with Bazel 0.25:
    
    - Make transitive starlark loads explicit
    - Update rules_closure to latest version
    - polygerrit_plugin: Demote compilation level to whitespace only
    
    Also update local build files to make transitive starlark loads
    explicit.
    
    Bug: Issue 10694
    Bug: Issue 10855
    Change-Id: I480b5a929a48ce327daf95d7f74e167e50aeed6d
    
  - Upgrade mockito-core to 2.28.2
    
    Change-Id: I2be328c62e3b20d3ebbe230637808e87dea3fcf5
    
  - Merge branch 'stable-2.14' into stable-2.15
    
    * stable-2.14:
      Make transitive starlark loads explicit
    
    Change-Id: I53c81d68d4be813e6bdfa230aea8a71cbadf5f6b
    
  - Make transitive starlark loads explicit
    
    This fixes the build with bazel 0.25.
    
    Bug: Issue 10855
    Change-Id: I480b5a929a48ce327daf95d7f74e167e50aeed6d
    
  - Make transitive starlark loads explicit
    
    This fixes the build with bazel 0.25.
    
    Bug: Issue 10855
    Change-Id: I480b5a929a48ce327daf95d7f74e167e50aeed6d
    

Former-commit-id: a67ce309d801a819fd939d515a68dfa9d5ebae93