Do not fail if user provides a too high/low label value in query
For label queries the max supported range for values is -4 to +4
(hard-coded in LabelPredicate). If the provided label value was too
high/low it could happen that we parsed a range where min was greater
than max. This led to an IllegalArgumentException [1] when we tried to
initialze a list with a size based on min and max. For queries that used
the 'label' predicate (e.g. "label:Code-Review>10") that exception was
caught and the user got a 400 Bad Request. If it was a default query
(e.g. "Code-Review>10") the exception caused a 500 Internal Server
Error.

Fix this by ensuring that for parsed ranges -4 <= min <= +4, -4 <= max
<= +4 and min <= max is always true.

We saw the exception below [1] when a user tried to query "size>1000"
which we interpret as label.

[1]
AutoRetry: restapi.change.QueryChanges failed, retry with tracing enabled [CONTEXT forced=true TRACE_ID="retry-on-failure-1574108318670-91eac85e" ]
java.lang.IllegalArgumentException: initialArraySize cannot be negative but was: -996
        at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39)
        at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:174)
        at com.google.gerrit.server.query.change.LabelPredicate.predicates(LabelPredicate.java:117)
        at com.google.gerrit.server.query.change.LabelPredicate.<init>(LabelPredicate.java:79)
        at com.google.gerrit.server.query.change.ChangeQueryBuilder.label(ChangeQueryBuilder.java:869)
        at com.google.gerrit.server.query.change.ChangeQueryBuilder.defaultField(ChangeQueryBuilder.java:1285)
        at com.google.gerrit.index.query.QueryBuilder.toPredicate(QueryBuilder.java:258)
        at com.google.gerrit.index.query.QueryBuilder.children(QueryBuilder.java:331)
        at com.google.gerrit.index.query.QueryBuilder.toPredicate(QueryBuilder.java:251)
        at com.google.gerrit.index.query.QueryBuilder.parse(QueryBuilder.java:224)
        at com.google.gerrit.index.query.QueryBuilder.parse(QueryBuilder.java:243)
        at com.google.gerrit.server.restapi.change.QueryChanges.query(QueryChanges.java:144)
        at com.google.gerrit.server.restapi.change.QueryChanges.apply(QueryChanges.java:121)
        at com.google.gerrit.server.restapi.change.QueryChanges.apply(QueryChanges.java:43)
        at com.google.gerrit.httpd.restapi.RestApiServlet.lambda$invokeRestReadViewWithRetry$3(RestApiServlet.java:723)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.google.gerrit.server.update.RetryHelper.executeWithTimeoutCount(RetryHelper.java:417)
        at com.google.gerrit.server.update.RetryHelper.executeWithAttemptAndTimeoutCount(RetryHelper.java:368)
        at com.google.gerrit.server.update.RetryHelper.execute(RetryHelper.java:271)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestEndpointWithRetry(RestApiServlet.java:820)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestReadViewWithRetry(RestApiServlet.java:718)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:501)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        ...

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: Icea364742485f9e6d7cc836cfc95c97d2a4569ba

Former-commit-id: 4b8eb7d919122801da81dade448d2c13de10ff0a