coverage.sh: Remove exclusion of auto_value_tests
The javatests/com/google/gerrit/common:auto_value_tests target no longer
exists.

Currently we get the following warning:
ERROR: Skipping '//javatests/com/google/gerrit/common:auto_value_tests':
no such target '//javatests/com/google/gerrit/common:auto_value_tests':
target 'auto_value_tests' not declared in package
'javatests/com/google/gerrit/common' defined by
/usr/local/google/home/ekempin/git/gerrit/javatests/com/google/gerrit/common/BUILD

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: I6c53073536d16e14e91fee57d3a7cff1aa6bd381

Former-commit-id: e3a400edfe41d646a4f7cbd01d885034f1ebef24