InvalidQueryException: Remove unused constructor
Change-Id: Icd150fe19d2acd8463302d6c3ca3444d1d0c0ee2

Former-commit-id: 3b25802fef6deb273eb3f121babbad084878eab5