OptionUtil: Use ImmutableList<String> instead of String[]
Change Id7911fb6d reduced the severity of ImmutableAnnotationChecker
to WARN because it was failing the build with errors like:

  error: [ImmutableAnnotationChecker] annotations should be immutable:
  'AutoAnnotation_OptionUtil_newOption' has field 'aliases' of type
  'java.lang.String[]', arrays are mutable

Fix this by using ImmutableList<String> instead of String[], and
change the severity of the check back to ERROR.

Change-Id: I72d6044a4d5422bf4e28c051b9a39168769a4d57

Former-commit-id: 9ab0d639b0b249660dbd7949f3078982bdc69ab5