lib/elasticsearch: restore jackson_dataformat_smile
As removing it in 40744d99f introduced a related NoClassDefFoundError
regression.

Bug: Issue 6094
Change-Id: I03c4801ae8c1cfb0b74ad39ef1398cd31225ba14

Former-commit-id: 31c040a2339545caeebd56ace11c7526f1f8f465